In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\rizne\Desktop\Munka fájlok\Python_files\pandas\pandas_project2_datacleaning\cafe_sales\dirty_cafe_sales.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
df.shape

(10000, 8)

In [7]:
df["Transaction ID"].nunique()

10000

In [8]:
df["Item"].nunique()

10

In [9]:
df["Item"].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [10]:
df["Item"].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [11]:
df.groupby("Item")["Price Per Unit"].unique()

Item
Cake                               [3.0, nan, UNKNOWN, ERROR]
Coffee                             [2.0, nan, ERROR, UNKNOWN]
Cookie                             [1.0, UNKNOWN, nan, ERROR]
ERROR       [1.5, 3.0, 5.0, nan, 4.0, 2.0, 1.0, UNKNOWN, E...
Juice                              [3.0, nan, UNKNOWN, ERROR]
Salad                              [5.0, ERROR, UNKNOWN, nan]
Sandwich                           [4.0, nan, ERROR, UNKNOWN]
Smoothie                           [4.0, nan, UNKNOWN, ERROR]
Tea                                [1.5, nan, ERROR, UNKNOWN]
UNKNOWN     [3.0, 1.0, 5.0, 4.0, 1.5, 2.0, nan, UNKNOWN, E...
Name: Price Per Unit, dtype: object

In [12]:
df["Item"]=df["Item"].replace(["ERROR","UNKNOWN"],pd.NA)

In [13]:
df["Quantity"].unique()

<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

In [14]:
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9962 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

In [16]:
df["Price Per Unit"].unique()

<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

In [17]:
df["Price Per Unit"]=pd.to_numeric(df["Price Per Unit"],errors="coerce")

In [18]:
df["Total Spent"].unique()

<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

In [19]:
df["Total Spent"]=pd.to_numeric(df["Total Spent"],errors="coerce")

In [20]:
df["Payment Method"].unique()

<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

In [21]:
df["Payment Method"]=df["Payment Method"].replace(["ERROR","UNKNOWN"],pd.NA)

In [22]:
df["Location"].unique()

<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [23]:
df["Location"]=df["Location"].replace(["ERROR","UNKNOWN"],pd.NA)

In [24]:
df["Transaction Date"].value_counts(dropna=False)

Transaction Date
NaN           159
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 368, dtype: int64

In [25]:
df["Transaction Date"].dropna().unique()

<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 367, dtype: str

In [26]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"],errors="coerce")

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

In [28]:
df.iloc[:, 1:].isna().all(axis=1).sum()

np.int64(0)

In [29]:
df.isna().sum(axis=1).value_counts().sort_index()

0    3089
1    4285
2    2136
3     439
4      47
5       4
Name: count, dtype: int64

In [30]:
df[df.isna().sum(axis=1) >= 4]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
104,TXN_7447872,Juice,2.0,NaN,6.0,NaN,NaN,NaT
434,TXN_4796350,NaN,NaN,4.0,12.0,NaN,Takeaway,NaT
551,TXN_4152036,NaN,NaN,3.0,6.0,Cash,NaN,NaT
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
727,TXN_8297135,NaN,2.0,4.0,NaN,NaN,NaN,2023-09-16
1170,TXN_7626939,Coffee,NaN,2.0,10.0,NaN,NaN,NaT
1377,TXN_8396271,NaN,2.0,NaN,2.0,NaN,NaN,2023-09-12
1379,TXN_5237569,Tea,3.0,NaN,4.5,NaN,NaN,NaT
1589,TXN_5245399,NaN,5.0,NaN,10.0,NaN,NaN,2023-12-25
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,NaN,2023-02-09
1786,TXN_1923349,NaN,4.0,NaN,6.0,NaN,NaN,2023-07-06
1889,TXN_1185118,NaN,5.0,3.0,NaN,NaN,NaN,NaT
2227,TXN_3200203,NaN,2.0,NaN,8.0,NaN,NaN,2023-12-04
2229,TXN_8498613,Sandwich,2.0,NaN,NaN,NaN,NaN,2023-11-08
2289,TXN_7524977,NaN,4.0,NaN,NaN,NaN,NaN,2023-12-09
2853,TXN_2505327,Juice,2.0,3.0,NaN,NaN,NaN,NaT
3013,TXN_1842697,NaN,5.0,NaN,15.0,NaN,NaN,2023-10-25
3142,TXN_3292043,Cookie,5.0,NaN,5.0,NaN,NaN,NaT
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07
3322,TXN_4081759,NaN,NaN,2.0,4.0,NaN,NaN,2023-09-30
3600,TXN_1784150,NaN,3.0,1.0,NaN,NaN,NaN,2023-03-10
3673,TXN_6500126,Smoothie,2.0,NaN,NaN,NaN,NaN,NaT
3779,TXN_7376255,NaN,NaN,NaN,25.0,NaN,In-store,2023-05-27
3805,TXN_6269540,NaN,NaN,4.0,12.0,NaN,NaN,2023-12-06
4092,TXN_1840897,NaN,1.0,NaN,5.0,NaN,NaN,2023-06-03
4152,TXN_9646000,NaN,2.0,NaN,NaN,NaN,In-store,2023-12-14
4656,TXN_2946861,NaN,3.0,3.0,NaN,NaN,NaN,2023-03-28
4735,TXN_9455737,NaN,3.0,5.0,15.0,NaN,NaN,NaT
5714,TXN_7263939,NaN,NaN,4.0,4.0,NaN,NaN,2023-08-08
5851,TXN_6184247,NaN,1.0,3.0,3.0,NaN,NaN,NaT
6192,TXN_9537106,NaN,NaN,4.0,12.0,NaN,NaN,2023-10-11
6225,TXN_6859249,Cookie,NaN,NaN,2.0,NaN,NaN,NaT
6399,TXN_3014967,Salad,NaN,5.0,5.0,NaN,NaN,NaT
6535,TXN_1022126,Tea,NaN,1.5,4.5,NaN,NaN,NaT
6674,TXN_3071092,Coffee,NaN,NaN,4.0,NaN,NaN,2023-09-08
6907,TXN_2194660,NaN,1.0,5.0,5.0,NaN,NaN,NaT
7478,TXN_9710982,NaN,4.0,NaN,16.0,NaN,NaN,2023-03-03
7923,TXN_9239309,Salad,4.0,5.0,NaN,NaN,NaN,NaT
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,NaN,2023-06-03
8788,TXN_2025634,NaN,1.0,4.0,4.0,NaN,NaN,NaT
8884,TXN_3811655,Smoothie,2.0,4.0,NaN,NaN,NaN,NaT
9212,TXN_7322317,Tea,1.0,NaN,NaN,NaN,NaN,2023-03-16
9278,TXN_1166001,NaN,NaN,3.0,15.0,Cash,NaN,NaT
9334,TXN_1565027,NaN,3.0,1.5,NaN,NaN,NaN,2023-03-16
9382,TXN_4255580,NaN,1.0,NaN,3.0,Cash,NaN,NaT
9425,TXN_2065683,NaN,3.0,NaN,6.0,NaN,NaN,2023-09-21
9454,TXN_1637131,NaN,4.0,NaN,6.0,Cash,NaN,NaT
9457,TXN_1852436,Juice,4.0,NaN,12.0,NaN,NaN,NaT
9610,TXN_4569448,NaN,1.0,3.0,3.0,NaN,NaN,NaT
9819,TXN_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19
9988,TXN_9594133,Cake,5.0,3.0,NaN,NaN,NaN,NaT

In [33]:
tsm=(df["Total Spent"].isna() & df["Quantity"].notna() & df["Price Per Unit"].notna())
df.loc[tsm,"Total Spent"]=(
    df.loc[tsm,"Quantity"] * df.loc[tsm,"Price Per Unit"]
)

In [42]:
df[["Total Spent","Quantity","Price Per Unit"]]

      Total Spent  Quantity  Price Per Unit
0             4.0       2.0             2.0
1            12.0       4.0             3.0
2             4.0       4.0             1.0
3            10.0       2.0             5.0
4             4.0       2.0             2.0
...           ...       ...             ...
9995          4.0       2.0             2.0
9996          3.0       3.0             1.0
9997          8.0       4.0             2.0
9998          3.0       3.0             1.0
9999         12.0       3.0             4.0

[10000 rows x 3 columns]

In [37]:
df["Total Spent"].isna().sum()

np.int64(40)

In [38]:
qm=(df["Quantity"].isna() & df["Total Spent"].notna() & df["Price Per Unit"].notna())
df.loc[qm,"Quantity"]=(
    df.loc[qm,"Total Spent"] / df.loc[qm,"Price Per Unit"]
)

In [39]:
df["Quantity"].isna().sum()

np.int64(38)

In [40]:
ppm=(df["Price Per Unit"].isna() & df["Total Spent"].notna() & df["Quantity"].notna())
df.loc[ppm,"Price Per Unit"]=(
    df.loc[ppm,"Total Spent"] / df.loc[ppm,"Quantity"]
)

In [41]:
df["Price Per Unit"].isna().sum()

np.int64(38)

In [43]:
df.loc[
    df[["Quantity", "Price Per Unit", "Total Spent"]].notna().sum(axis=1) == 1,
    ["Quantity", "Price Per Unit", "Total Spent"]
]

      Quantity  Price Per Unit  Total Spent
65         3.0             NaN          NaN
236        NaN             5.0          NaN
278        NaN             3.0          NaN
629        NaN             NaN         12.0
641        NaN             3.0          NaN
738        NaN             4.0          NaN
912        NaN             NaN         20.0
1008       NaN             NaN          3.0
1436       NaN             NaN          6.0
1482       NaN             NaN         16.0
1674       2.0             NaN          NaN
1761       4.0             NaN          NaN
2229       2.0             NaN          NaN
2289       4.0             NaN          NaN
2330       NaN             NaN          5.0
2585       3.0             NaN          NaN
2796       NaN             3.0          NaN
3162       3.0             NaN          NaN
3203       NaN             4.0          NaN
3224       NaN             2.0          NaN
3401       NaN             1.5          NaN
3598       1.0             NaN          NaN
3635       NaN             NaN          1.0
3673       2.0             NaN          NaN
3779       NaN             NaN         25.0
4021       2.0             NaN          NaN
4152       2.0             NaN          NaN
4257       NaN             2.0          NaN
5639       NaN             NaN          6.0
5841       NaN             1.0          NaN
5845       NaN             NaN          8.0
6225       NaN             NaN          2.0
6661       NaN             NaN          1.0
6674       NaN             NaN          4.0
7029       NaN             2.0          NaN
7035       5.0             NaN          NaN
7230       2.0             NaN          NaN
7244       5.0             NaN          NaN
7297       NaN             4.0          NaN
7568       5.0             NaN          NaN
7597       NaN             NaN          9.0
7686       5.0             NaN          NaN
8021       NaN             5.0          NaN
8128       3.0             NaN          NaN
8443       NaN             4.0          NaN
8465       NaN             2.0          NaN
8479       NaN             4.0          NaN
8497       3.0             NaN          NaN
8574       NaN             3.0          NaN
8669       NaN             NaN          3.0
8732       NaN             1.0          NaN
8975       NaN             NaN          7.5
9212       1.0             NaN          NaN
9464       NaN             NaN          3.0
9590       NaN             4.0          NaN
9819       NaN             NaN         20.0
9869       NaN             2.0          NaN
9893       2.0             NaN          NaN

In [47]:
df[["Quantity", "Price Per Unit", "Total Spent"]].notna().sum(axis=1).value_counts()

3    9942
1      58
Name: count, dtype: int64

In [48]:
uncalculable = df.loc[
    df[["Quantity", "Price Per Unit", "Total Spent"]].notna().sum(axis=1) == 1,
    ["Quantity", "Price Per Unit", "Total Spent"]
]

In [49]:
len(uncalculable)

58

58 values are unattainable from the data

In [50]:
df["Transaction ID"].nunique()

10000

In [51]:
df["Transaction ID"].duplicated().sum()

np.int64(0)